---
title: "MAGIC Parents SNP Analysis"
output: html_notebook
author: "Joe Edwards"
---

```{r}
library(tidyverse)
library(fuzzyjoin)
```

```{r}
setwd("~/JOE/Arabidopsis/MAGIC/SNP_CALLING/")
```

```{r}
samples <- scan("../RAWDATA/samples", what = "character")
vcf_files <- dir("../SNP_CALLING/HQ_CALLS/", pattern = '*.vcf', full.names = T)
gff <- read.table("~/tutorial/reference/TAIR10_GFF3_genes_transposons.gff", header = F) %>% 
  filter(V3 == "mRNA")
```

```{r}
vcf_read <- function(data){
  f <- readr::read_tsv(data, comment = "##") %>% 
    mutate(SampleID = gsub("\\.vcf", "", data)) %>% 
    rename("Chr" = !!names(.[1])) %>% 
    mutate(Chr = paste("Chr", Chr, sep = ""))
  return(f[,-10])
}

AT_DATA <- vcf_files %>% 
  map(vcf_read) %>% 
  reduce(rbind) %>% 
  mutate(SampleID = gsub(".*Pool[0-9]_", "", SampleID), SampleID = gsub("_hq_calls", "", SampleID))
```

```{r}
gene_snps <- fuzzy_left_join(AT_DATA, gff,
                             by = c("Chr" = "V1",
                                    "POS" = "V4",
                                    "POS" = "V5"),
                             match_fun = list(`==`, `>=`, `<=`))
  
```

